<?php

/**
 * @file
 * Provides a webform element for a selecting an image.
 */

use Drupal\Core\Url;
use Drupal\Core\Config\Entity\ConfigEntityInterface;
use Drupal\Core\Serialization\Yaml;

/**
 * Implements hook_webform_libraries_info().
 */
function webform_image_select_webform_libraries_info() {
  $libraries = [];
  $libraries['jquery.image-picker'] = [
    'title' => t('jQuery: Image Picker'),
    'description' => t('A simple jQuery plugin that transforms a select element into a more user friendly graphical interface.'),
    'notes' => t('Image Picker is used by the Image select element.'),
    'homepage_url' => Url::fromUri('https://rvera.github.io/image-picker/'),
    'download_url' => Url::fromUri('https://github.com/rvera/image-picker/archive/0.3.0.zip'),
    'version' => '0.3.0',
    'elements' => ['webform_image_select'],
    'optional' => FALSE,
  ];
  return $libraries;
}

/******************************************************************************/
// Lingotek integration.
/******************************************************************************/

/**
 * Implements hook_lingotek_config_entity_document_upload().
 */
function webform_image_select_lingotek_config_entity_document_upload(array &$source_data, ConfigEntityInterface &$entity, &$url) {
  switch ($entity->getEntityTypeId()) {
    case 'webform_image_select_images';
      // Convert images YAML string to an associative array.
      $source_data['images'] = Yaml::decode($source_data['images']);
      break;
  }
}

/**
 * Implements hook_lingotek_config_entity_translation_presave().
 */
function webform_image_select_lingotek_config_entity_translation_presave(ConfigEntityInterface &$translation, $langcode, &$data) {
  switch ($translation->getEntityTypeId()) {
    case 'webform_image_select_images';
      /** @var \Drupal\webform_image_select\WebformImageSelectImagesInterface $translation */
      // Convert images associative array back to YAML string.
      $translation->setImages($data['images']);
      $data['images'] = Yaml::encode($data['images']);
      break;
  }
}
